kind: Deployment
apiVersion: apps/v1
metadata:
  name: 'y'
  namespace: kubesphere-sample-dev
  labels:
    app: 'y'
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: project-regular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'y'
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 'y'
      annotations:
        kubesphere.io/creator: project-regular
    spec:
      containers:
        - name: container-gzbw6z
          image: 'zhanghl0613/devops-sample:v10'
          ports:
            - name: http-1
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
